### ISSUE TITLE
Add multi-tier review

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-decision#2]
- [x] Add a `Finalized` field to `Decision` and `DecisionHistory` structs. (Default value is `false`)
- [x] Add an endpoint to set this Field to `true` which finalizes the decision
- [x] Block further reviews on finalized decisions
- [x] When a user gets their own decision is should appear as `PENDING` until finalized

**Comment by PradyumnaShome** [comment]
@ASankaran I need some more clarification on the specifications of the endpoint.
1. I added the fields and set both to `validate:"required"`.
2. Should I return the decision as a response?
3. I've set up the update decision endpoint to check if a decision is finalized. How do we respond to an attempt to update a `Finalized` `Decision`? I've currently set it up to respond with the current decision.
4. Could you clarify more on this? Is this basically another way of saying that the default value of `Status` should be `PENDING`?

**Comment by ASankaran** [comment]
1. Right idea, but you can't use the `required` validation on bool. So we'll just make no finalized field default to `false` instead.
2. Yes, return the entire decision history
3. Return an `UnprocessableError`. We want to make it clear to the user that the decision was not modify. 
4. When a user hits `/decision/` right now we return them their current decision. With multi-tiered review, they may be `ACCEPTED`, but not finalized. In this case they should see their decision as `PENDING`. This endpoint is handled by `GetCurrentDecision`.
