### ISSUE TITLE
Users should not be able to see their entire decision history

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-decision#9]
- [x] Remove the list of past decisions from the `GET /decision/` endpoint

This endpoint is handled by `GetCurrentDecision`. This function should remove the history before encoding the decision into json to send to the user.

**Comment by PradyumnaShome** [comment]
Should we return an empty `history` array / slice, or should copy everything into a `Decision` struct instead?

**Comment by ASankaran** [comment]
We should probably just have a new struct called something like `DecisionView`. This struct would only contain the `Status` field from the decision. All the other data is only meant for internal use.
